### ISSUE TITLE
'ctools-layout-generator' is not in the npm registry.

### ISSUE THREAD

**Issue by danbohea** [pixelwhip/generator-ctools-layout#1]
Running `npm install ctools-layout-generator -g` throws an error along the lines of:

```
'ctools-layout-generator' is not in the npm registry.
```
It also suggests that I should:

```
You should bug the author to publish it (or use the name yourself!) 
```

Contents of npm-debug.log:

```
0 info it worked if it ends with ok
1 verbose cli [ 'node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   'ctools-layout-generator',
1 verbose cli   '-g' ]
2 info using npm@2.1.18
3 info using node@v0.10.35
4 verbose node symlink /usr/local/bin/node
5 silly cache add args [ 'ctools-layout-generator', null ]
6 verbose cache add spec ctools-layout-generator
7 silly cache add parsed spec { raw: 'ctools-layout-generator',
7 silly cache add   scope: null,
7 silly cache add   name: 'ctools-layout-generator',
7 silly cache add   rawSpec: '',
7 silly cache add   spec: '*',
7 silly cache add   type: 'range' }
8 verbose addNamed ctools-layout-generator@*
9 silly addNamed semver.valid null
10 silly addNamed semver.validRange *
11 silly addNameRange { name: 'ctools-layout-generator', range: '*', hasData: false }
12 silly mapToRegistry name ctools-layout-generator
13 silly mapToRegistry using default registry
14 silly mapToRegistry registry https://registry.npmjs.org/
15 silly mapToRegistry uri https://registry.npmjs.org/ctools-layout-generator
16 verbose addNameRange registry:https://registry.npmjs.org/ctools-layout-generator not in flight; fetching
17 verbose request uri https://registry.npmjs.org/ctools-layout-generator
18 verbose request no auth needed
19 info attempt registry request try #1 at 09:54:57
20 verbose request id 3cee50db8f22bcb9
21 http request GET https://registry.npmjs.org/ctools-layout-generator
22 http 404 https://registry.npmjs.org/ctools-layout-generator
23 verbose headers { date: 'Fri, 30 Jan 2015 09:54:58 GMT',
23 verbose headers   server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
23 verbose headers   'content-type': 'application/json',
23 verbose headers   'cache-control': 'max-age=0',
23 verbose headers   'content-length': '52',
23 verbose headers   'accept-ranges': 'bytes',
23 verbose headers   via: '1.1 varnish',
23 verbose headers   age: '0',
23 verbose headers   'x-served-by': 'cache-ams4129-AMS',
23 verbose headers   'x-cache': 'MISS',
23 verbose headers   'x-cache-hits': '0',
23 verbose headers   'x-timer': 'S1422611698.381036,VS0,VE161',
23 verbose headers   'keep-alive': 'timeout=10, max=50',
23 verbose headers   connection: 'Keep-Alive' }
24 silly get cb [ 404,
24 silly get   { date: 'Fri, 30 Jan 2015 09:54:58 GMT',
24 silly get     server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
24 silly get     'content-type': 'application/json',
24 silly get     'cache-control': 'max-age=0',
24 silly get     'content-length': '52',
24 silly get     'accept-ranges': 'bytes',
24 silly get     via: '1.1 varnish',
24 silly get     age: '0',
24 silly get     'x-served-by': 'cache-ams4129-AMS',
24 silly get     'x-cache': 'MISS',
24 silly get     'x-cache-hits': '0',
24 silly get     'x-timer': 'S1422611698.381036,VS0,VE161',
24 silly get     'keep-alive': 'timeout=10, max=50',
24 silly get     connection: 'Keep-Alive' } ]
25 verbose stack Error: 404 Not Found: ctools-layout-generator
25 verbose stack     at CachingRegistryClient.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:241:14)
25 verbose stack     at Request._callback (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:172:14)
25 verbose stack     at Request.self.callback (/usr/local/lib/node_modules/npm/node_modules/request/request.js:373:22)
25 verbose stack     at Request.emit (events.js:98:17)
25 verbose stack     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1318:14)
25 verbose stack     at Request.emit (events.js:117:20)
25 verbose stack     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1266:12)
25 verbose stack     at IncomingMessage.emit (events.js:117:20)
25 verbose stack     at _stream_readable.js:944:16
25 verbose stack     at process._tickCallback (node.js:442:13)
26 verbose statusCode 404
27 verbose pkgid ctools-layout-generator
28 verbose cwd /Users/danbohea
29 error Darwin 13.4.0
30 error argv "node" "/usr/local/bin/npm" "install" "ctools-layout-generator" "-g"
31 error node v0.10.35
32 error npm  v2.1.18
33 error code E404
34 error 404 Not Found: ctools-layout-generator
34 error 404
34 error 404 'ctools-layout-generator' is not in the npm registry.
34 error 404 You should bug the author to publish it (or use the name yourself!)
34 error 404
34 error 404 Note that you can also install from a
34 error 404 tarball, folder, http url, or git url.
35 verbose exit [ 1, true ]

```

**Comment by danbohea** [comment]
All sorted now. The command I was running was incorrect (taken from the original version of http://atendesigngroup.com/blog/creating-custom-ctools-layout-plugins-yeoman). Running the following works, as suggested by this project's README (notice that the placement of the global switch):

```
npm install -g generator-ctools-layout

```
